services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./data/AAAU.csv:/tmp/AAAU.csv
      - ./data/bitcoin_transformed.csv:/tmp/bitcoin_transformed.csv
      - ./data/dirtydata.csv:/tmp/dirtydata.csv
      - ./data/salaries.csv:/tmp/salaries.csv
      - ./data/customers.csv:/tmp/customers.csv
    ports:
      - "5432:5432"

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "${MLFLOW_PORT:-5001}:5000"
    environment:
      MLFLOW_S3_ENDPOINT_URL: "http://minio:9000"
      MLFLOW_S3_IGNORE_TLS: "true"
      AWS_ACCESS_KEY_ID: "mflow"
      AWS_SECRET_ACCESS_KEY: "mflow123"
    entrypoint: mlflow server --backend-store-uri postgresql+psycopg2://mlflow:mlflow123@postgres/mlflow --default-artifact-root s3://mlflow/ --artifacts-destination s3://mlflow/ -h 0.0.0.0
    depends_on:
      - minio
      - postgres

  minio:
    image: minio/minio:latest
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-8900}:8900"
    environment:
      MINIO_ACCESS_KEY: "mlflow"
      MINIO_SECRET_KEY: "mlflow123"
    volumes:
      - "mlflow-minio:/data/minio"
    command: 'minio server /data/minio --console-address ":8900"'

  postgres:
    image: postgres:16-alpine
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "mlflow"
      POSTGRES_PASSWORD: "mlflow123"
      POSTGRES_DB: "mlflow"
    volumes:
      - "mlflow-postgres:/var/lib/postgresql/data"


volumes:
  db_data:
  mlflow-minio:
    driver: local
  mlflow-postgres:
    driver: local